FROM --platform=linux/amd64 nvidia/cuda:12.3.0-base-ubuntu20.04
# Use the ubuntu nvidia base with cuda


# Do all tasks to be done with root privileged
RUN  apt update && \
     apt install -y wget git nano tmux && \
     apt-get clean && rm -rf /var/lib/apt/lists/*

## Switch to the local user
RUN groupadd -r upwaszak && useradd -r -g upwaszak lbrunsch
USER lbrunsch
WORKDIR /home/lbrunsch

## Install conda in your home
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh  \
    && bash ~/miniconda.sh -b -p $HOME/miniconda \
    && rm ~/miniconda.sh

# Add miniconda to path
ENV PATH /home/lbrunsch/miniconda/bin:${PATH}

## Create a conda env with required packages and Python 3.8
RUN conda install mamba -n base -c conda-forge -y
RUN mamba create -n venv python=3.8 -y
COPY environment.yml /tmp/environment.yml
RUN mamba env update -n venv -f /tmp/environment.yml
RUN echo "source activate venv" > ~/.bashrc

ENV PATH /home/lbrunsch/.conda/envs/venv/bin:$PATH